### ISSUE TITLE
netgen not available for installation via gem

### ISSUE THREAD

**Issue by GalaxyGorilla** [rwestphal/netgen#1]
```
 % gem install netgen
ERROR:  Could not find a valid gem 'netgen' (>= 0) in any repository
ERROR:  Possible alternatives: netgeo, NumGen, btgen, defgen, eigen
```

Maybe a re-upload is necessary?

**Comment by rwestphal** [comment]
The error you got is because netgen was never published yet.

The reason for not publishing it is because I consider the code to be too immature and incomplete at this point. But maybe this is something we can change in the following months :)
